# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17093b78becabd49514515b4f6404c15f7ea962f0bf5a9ccf5e4b84033e8cde4fbf1f3fa1ce12394a07f4c5333a909141d43fe2aa1d03228d44f4bb0963e3283

# Use different runs of `rake secret` for development and test
test:
  secret_key_base: b7360363617eb8a57491c404ed6ad4f3f603aa9d3f43707961424a32e7f5c47d3d4effd99620e404d0c9d58279a33d8a2ecf210ce9ae0dadaba7a82f7c9e8fc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
